### ISSUE TITLE
A question about accepting Tune query

### ISSUE THREAD

**Issue by VandalByte** [BreadMaker/grub-tune-tester#10]
Hi there @BreadMaker, first of all thanks for this cool project. I actually had a question to ask.
I'm not a web developer and I don't know if it can be done in github pages but, can the webpage be made so that it can accept a song query and play it? Instead of like selecting `custom input` and pasting the notes. Cause I was thinking, it would be a great functionality to have in our page [here](https://github.com/vandalsoul/grub-tweaks/blob/main/docs/GRUB%20INIT-TUNE%20CHEATSHEET.md)

**Comment by BreadMaker** [comment]
Yes, this is a great idea! I'm currently reviewing the related #12 PR, which I'll accept and expand. A future related commit will close this issue.
