### ISSUE TITLE
Better UI

### ISSUE THREAD

**Issue by BreadMaker** [BreadMaker/grub-tune-tester#4]
Current UI works, but it's not completely intuitive, especially when creating tunes. This has to improve.

**Comment by LeoJhonSong** [comment]
It would be much better if we could give name to a tune and the names can show up when choosing one to play

**Comment by BreadMaker** [comment]
UX has substantially improved with v0.5.0 release, adding information about what it needs to be done while inputting manually.

**Comment by BreadMaker** [comment]
> It would be much better if we could give name to a tune and the names can show up when choosing one to play

Now the dropdown lists the tune descrptions and the tune line is displayed in another UI element.
